### ISSUE TITLE
Should we move the site to Polymer or MTL?

### ISSUE THREAD

**Issue by imkarthikk** [skcript/gdgchennai#3]
I think the tech behind this site is too simple, and our learning curve is too small here. Moving to Polymer or Material Design Lite would give us a better learning curve. 

What do you guys think?

**Comment by mukilane** [comment]
Yeah. 
In my opinion, being a GDG site, it should represent Google's Material Design language. 
Moving to Polymer or Angular would be my suggestion. 
MDLite is somewhat basic, and lacks many features.

**Comment by imkarthikk** [comment]
@mukilane That's the same thought process I had. But then, GDG Chennai will always be static, and it is just to display the happenings. So MDL might be a good choice.

**Comment by mukilane** [comment]
@imkarthikk 
Yeah, we can serve a static site with MDL, but it just stops there. 
We must move on,  right ?
Recently Google announced Physical web. And the standards are high now. 
The Google I/O website is built on Polymer and it has offline caching, notifications, sign-in, etc. just for an serving static content.
I just thought it would be great if we could match GDGChn with that.

**Comment by imkarthikk** [comment]
@mukilane Again, I agree. But I might have a different perspective on this. The goal of GDG Chennai's Website is to just follow the best practices of current web technologies. But yes, Physical Web is interesting, we will have to wait until we go ahead and do something of that sort. 

Would you like to work with us on a Open Source Project involving Physical Web?

**Comment by mukilane** [comment]
@imkarthikk  
Yeah I am glad to work with you on that.

**Comment by imkarthikk** [comment]
@mukilane : Perfect. We will kick that off in a while. :)
